name: myenv
channels:
  - anaconda
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.11.0=py38h06a4308_0
  - astunparse=1.6.3=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - blinker=1.4=py38_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.12.8=h06a4308_0
  - cachetools=4.1.1=py_0
  - certifi=2020.12.5=py38h06a4308_0
  - cffi=1.14.4=py38h261ae71_0
  - chardet=3.0.4=py38h06a4308_1003
  - click=7.1.2=py_0
  - cryptography=3.2.1=py38h3c74f83_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - docopt=0.6.2=py38_0
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - gast=0.3.3=py_0
  - glib=2.66.1=h92f7085_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=h71b1129_1002
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py38hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py38hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.19.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py38h06a4308_1
  - jpeg=9b=h024ee3a_2
  - jsonpickle=1.4.2=pyhd3eb1b0_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py38h06a4308_0
  - keras=2.4.3=0
  - keras-base=2.4.3=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.3.0=py38h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.3=py38h06a4308_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - munch=2.5.0=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.4.1=hbb512f6_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1i=h27cfd23_0
  - opt_einsum=3.1.0=py_0
  - parso=0.7.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.0.1=py38he98fc37_0
  - prompt-toolkit=3.0.8=py_0
  - protobuf=3.13.0.1=py38he6710b0_1
  - ptyprocess=0.6.0=pyhd3eb1b0_2
  - py-cpuinfo=7.0.0=py_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.7.2=pyhd3eb1b0_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=20.0.0=pyhd3eb1b0_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - pyzmq=20.0.0=py38h2531618_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scipy=1.5.2=py38h0b6359f_0
  - setuptools=50.3.2=py38h06a4308_2
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=gpu_py38hb782248_0
  - tensorflow-base=2.2.0=gpu_py38h83e3d50_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - termcolor=1.1.0=py38_1
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.0.5=py_0
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.36.0=pyhd3eb1b0_0
  - wrapt=1.12.1=py38h7b6447c_1
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - classification-models==0.1
    - cloudpickle==1.4.1
    - ffmpeg-python==0.2.0
    - future==0.18.2
    - heart-echo==1.1.1
    - image-classifiers==1.0.0
    - joblib==0.15.1
    - keras-applications==1.0.8
    - minisom==2.2.7
    - opencv-python==4.4.0.42
    - panda==0.3.1
    - pandas==1.1.2
    - pip==20.2.4
    - pytz==2020.1
    - pyyaml==5.3.1
    - scikit-learn==0.22.2
    - sklearn==0.0
    - tensorflow-probability==0.10.0
    - threadpoolctl==2.1.0
    - torch==1.6.0
    - tqdm==4.48.2
    - utkface==0.1
prefix: /cluster/home/lauraman/software/anaconda/envs/myenv
